### PR TITLE
V2 WVW

### PR DESCRIPTION
**Pull request by Vyrolan**
I've built out the V2 WVW interfaces.  I used the existing V1 WVW as a base and followed the patterns of the other existing V2 classes.  I tried to keep changes to the core classes minimal while also providing access to all the new data in V2.  The ugliest parts were the new match repositories since there is no "matchup" in V2 but rather just a simple string id...and I also wanted to support the match lookup by world id.

I also added support for the "type" field provided for Maps in both V1 and V2.  I wanted that for distinguishing between two maps called " Alpine Borderlands" without using the coordinates.

Open to comments/suggestions/questions.

### CODE REVIEW

**Comment by Ruhrpottpatriot** [comment]
AppVeyor is failing to build the solution. I take it you can compile it on your end? I don't have the time to fully check this, so I'm trusting you on this.

**Comment by Vyrolan** [comment]
Yea on the top of my branch I can build fine.  Not sure why the AppVeyor is failing.   I took a fork and opened the existing .sln in VS 2015 Pro and made my changes/additions...it all builds there for me and all tests build/run/pass.

**Comment by Vyrolan** [comment]
I just reverted that last commit on there about serialization...that's something I was doing for my purposes but probably doesn't need to be in the main repo.  I hadn't intended to push that to this branch...my apologies.

**Comment by Vyrolan** [comment]
Pushed up some more additions...built out the wvw objectives for V2 since we can get a lot more details about them in V2 than just the name.

**Comment by Ruhrpottpatriot** [comment]
Good stuff! I'll merge it this week when I have time to make a new release.

**Comment by Vyrolan** [comment]
Cool.   While far from exhaustive testing, I am using builds from my branch pretty extensively in my app and having no issues...  So a lot of the paths pulling down match stats, match objectives, etc are all being hit including the async paths.  I'm also using the new objective details and everything seems good.  Let me know if you see any problems on your end.

**Pull request merged**
